=== JBearded/ActionStatics/src/main/resources/statics.dtd
<!ELEMENT static (config,schedulers)>
<!ELEMENT config (from,to,max-thread)>
<!ELEMENT from ANY>
<!ELEMENT to ANY>
<!ELEMENT max-thread ANY>
<!ELEMENT schedulers (scheduler*)>
<!ELEMENT scheduler (job*)>
<!ELEMENT job EMPTY>
<!ATTLIST scheduler
        delay CDATA #REQUIRED
        interval CDATA #REQUIRED
        timeout CDATA #REQUIRED
        name CDATA #REQUIRED
        >
<!ATTLIST job
        action CDATA #REQUIRED
        file CDATA #REQUIRED
        >

=== JBearded/ActionStatics/src/test/resources/static.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE static SYSTEM "statics.dtd">
<static>
    <config>
        <from>http://www.domain.com</from>
        <to>/data/static/</to>
        <max-thread>20</max-thread>
    </config>
    <schedulers>
        <scheduler delay="5" interval="5" timeout="120" name="html_scheduler">
            <job action="/index.action" file="index.html"></job>
        </scheduler>
        <scheduler delay="10" interval="10" timeout="120" name="json_scheduler">
            <job action="/page.action?page=1" file="page_1.json"></job>
            <job action="/page.action?page=2" file="page_2.json"></job>
        </scheduler>
    </schedulers>
</static>
